services:

    # Contao frontend module Pnwscm60\ContaoPbworkBundle\Controller\FrontendModule\ErfassenController
    # We used annotations for tagging the frontend module category, the frontend module type and the frontend module template
    Pnwscm60\ContaoPbworkBundle\Controller\FrontendModule\ErfassenController:
        tags:
            - { name: container.service_subscriber }
        public: true
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    

